dataset: 
  module: datasets.mnist
  root: data
  raw: data/raw
  batch_size: 32


scheduler: 
  num_timesteps: 1000
  beta_start: 0.0001
  beta_end: 0.02
  zero_snr: False

model:
  module: ""
  im_channels: 1
  time_emb_dim: 128
  down_blocks: 
    - in_channels: 32
      out_channels: 64
      t_emb_dim: 128
      down_sample: True
      num_heads: 16
      num_layers: 2
      attn: False
      norm_channels: 16
      normtype: group
    - in_channels: 64
      out_channels: 128
      down_sample: False
      attn: True
      t_emb_dim: 128
      num_heads: 16
      num_layers: 2
      norm_channels: 16
      normtype: group
  mid_blocks:
    - in_channels: 128
      out_channels: 128
      attn: True
      t_emb_dim: 128
      num_heads: 16
      num_layers: 2
      norm_channels: 16





trainer:
  num_epochs: 150
  lr: 0.001
  checkpoint_interval: 20
  validation_interval: 10
  flush_logs_every_n_steps: 1

meta:
  modelname: unet
